# Site settings
title:       Just Write
author:      Ellen
description: "记录当下"
# baseurl:     "/Ellen Space"
url:         "https://ellenSun815.github.io"

# Social Links
# email:            safe@masha.space
# twitter_username: syr1993815
# github_username:  ellenSun815

# Build settings
markdown: kramdown
permalink: pretty
